spring.application.name=tds_app_exemplo

# Connection URL
spring.datasource.url=jdbc:mariadb://localhost:3306/tads_app_exemplo?createDatabaseIfNotExist=true
# Credentials
spring.datasource.username=root
spring.datasource.password=${MARIADB_SECRET:mariadb}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
