spring.application.name=tds_app_exemplo

# Connection URL
spring.datasource.url=jdbc:mariadb://localhost:3306/tads_app_exemplo?createDatabaseIfNotExist=true
# Credentials
spring.datasource.username=root
spring.datasource.password=${MARIADB_SECRET:mariadb}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JPA
# Hibernate ddl auto (create, create-drop, update, none): com "update" o esquema do database é automaticamente
# modificado, conforme as anotações JPA nas entidades Java da camada de modelo.
spring.jpa.hibernate.ddl-auto=update
# JPA-SQL (as propriedades abaixo instruem o Spring Boot a imprimir o SQL e formatá-lo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# adia a inicialização da execução dos scripts para depois da criação dos EntityManager do JPA (o padrão é o script executar antes do JPA)
spring.jpa.defer-datasource-initialization=true
# ordena a execução dos scripts do arquivo data.sql (Valor na primeira execução always. Lembre de colocar para never depois da primeira execução)
spring.sql.init.mode=always
# Configura para ignorar os erros ao tentar repopular as tabelas (já que o spring.sql.init.mode=always está true)
spring.sql.init.continue-on-error=true

# Secret para geração do token JWT
# As chaves indicam ao Spring Boot para ele procurar por uma variável de ambiente a partir do valor que está nela.
# Após os : é o valor que ele utiliza caso não localize a variável de ambiente. No caso, procura por JWT_SECRET, senão, aplica 12345678 x 4 (32 bits, conforme especificação JWT do Spring Security)
api.security.token.secret=${JWT_SECRET:12345678123456781234567812345678}

#Atrasa a inicialização do Hikari para sincronizar a inicialização do banco de dados com o Spring Boot no Docker
spring.datasource.hikari.initialization-fail-timeout=30000
